name: grace_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nltk=3.6.5
  - pandas=1.3.4
  - pip=21.2.4
  - python=3.9.7
  - pip:
    - einops==0.4.1
    - higher==0.2.1
    - hydra-core==1.2.0
    - numpy==1.24.3
    - torch==2.0.0
    - transformers==4.20.1
    - wandb==0.13.2
    - datasets==2.10.1
    - jsonlines==3.1.0
    - sentencepiece==0.1.97
    - matplotlib==3.7.2
    - scikit-learn
